language: scala

scala:
  - 2.12.6

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION assembly

  - find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  email: false